### ISSUE TITLE
Create asset Gem with OTTO robots

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#123]
Separate OTTO robots into their own asset Gem (Both in one)

**Comment by aniafafe** [comment]
Created here: https://github.com/o3de/o3de-extras/pull/540

**Comment by jhanca-robotecai** [comment]
Please note, that Otto gem is [created and ready to use](https://github.com/RobotecAI/o3de-otto-robots-gem). 

It should be double-checked if all changes in this repo were integrated into the gem (e.g. #255, #245, #239, #236, #230, ...?)
Finally, all Otto-related code should be removed from this repository. Gem should be used instead.
