### ISSUE TITLE
Create asset Gem with human

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#124]

**Comment by aniafafe** [comment]
Should this Gem contain a prefab with a ready-for-user setup for human movement or just a human prefab?

**Comment by aniafafe** [comment]
Decision after discussion: It should contain a prefab with a ready-for-user setup for human movement.

**Comment by jhanca-robotecai** [comment]
[HumanWorker Gem](https://github.com/RobotecAI/o3de-humanworker-gem)
