### ISSUE TITLE
Create Asset Gem with UR arms

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#125]
UR10 and UR20

**Comment by jhanca-robotecai** [comment]
Please note, that UR10 was modified when compared to the source (improved meshes and textures), while UR20 was not. Should UR20 be changed as well?

**Comment by pawelbudziszewski** [comment]
Work on UR20 visuals is in progress

**Comment by jhanca-robotecai** [comment]
[UR10 and UR20 Robots Gem](https://github.com/RobotecAI/o3de-ur-robots-gem)
