### ISSUE TITLE
Prepare and practice the import scenario, create a recording.

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#126]
Recorded video 3 minutes long, showcasing the following:​

1. Start: simulation project created from a template is built, and we are running it from console (assets were pre-built). Explain that this is how you can start yourself when using a pre-built docker.​
1.  Open a level and quickly summarize this template and what we start with.​
3.  Remove the template robot and talk about replacing it with another one.​
5.  Open the Robot Importer and follow the steps to import a robot from URDF.​
7.  Place the robot in the scene by dragging it, position it.​
9.  Discuss what is missing after the import, and what needs to be adjusted.​
11.  Add a lidar sensor component that we want as well as vehicle dynamics.​
13.  Change configuration of vehicle dynamics.​
15.  Play the simulation and steer the robot with rqt_robot_steering (or manually).​
17.  Close the tool and run nav2 stack with RViz2 (launch files from the template should be good, if not, show quick adjustment).​
19.  Give the robot a goal through RViz2 and watch it go!

**Comment by jhanca-robotecai** [comment]
The scenario was prepared and the recording was completed.
