### ISSUE TITLE
Optimize asset sizes

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#163]
Currently the project is large (in terms of GB) and takes plenty of time to process assets. Many of these are too detailed or can be otherwise optimized. The task is to identify such assets and optimize them.

**Comment by arturkamieniecki** [comment]
I looked at the file structure and identified some big files. And I included screenshots of their sizes and locations.
A good tool (which I used for this) is ncdu. It analyzes the sizes of each folders and files.

![Screenshot from 2023-10-02 15-09-16](https://github.com/RobotecAI/ROSCon2023Demo/assets/130671280/bb122843-1a0e-43e5-9d89-bd74278e89a9)
![Screenshot from 2023-10-02 15-09-21](https://github.com/RobotecAI/ROSCon2023Demo/assets/130671280/d49f2bc5-d9c8-4308-b5e4-2bf40de00831)
![Screenshot from 2023-10-02 15-09-35](https://github.com/RobotecAI/ROSCon2023Demo/assets/130671280/24608f9d-91b4-4c78-8d4c-6a17363c8c8b)
![Screenshot from 2023-10-02 15-09-43](https://github.com/RobotecAI/ROSCon2023Demo/assets/130671280/ca501b6b-0875-43b6-9885-68300d9178a4)
![Screenshot from 2023-10-02 15-09-50](https://github.com/RobotecAI/ROSCon2023Demo/assets/130671280/5590b357-f852-41d1-8648-14d90b27a87c)
![Screenshot from 2023-10-02 15-10-47](https://github.com/RobotecAI/ROSCon2023Demo/assets/130671280/7825fc3d-abf9-4c35-9bed-ea200eeb200a)

**Comment by arturkamieniecki** [comment]
Lossles compression of the files reduces only by around 1%. Lossy compression can be used (for example pngquant). During test this can decrease file sizes by 50%.

**Comment by arturkamieniecki** [comment]
Simple compression of files using pngquant yields an improvement of around 200MB.

**Comment by arturkamieniecki** [comment]
This simple script that decreases all resoultion of .png files by half. This decreases the size of /Assets by around 1GB.

```py
import os
import argparse
from PIL import Image

# Function to decrease resolution of a .png file by half and overwrite the original file
def decrease_resolution(file_path):
    try:
        image = Image.open(file_path)
        width, height = image.size
        new_width, new_height = width // 2, height // 2

        resized_image = image.resize((new_width, new_height), Image.ANTIALIAS)

        # Overwrite the original file
        resized_image.save(file_path)

        print(f"Resized {file_path} to half resolution (overwrote the original file)")
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

# Function to find and process all .png files
def process_all_png_files(root_dir):
    for root, _, files in os.walk(root_dir):
        for filename in files:
            if filename.endswith(".png"):
                file_path = os.path.join(root, filename)
                decrease_resolution(file_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Decrease resolution of .png files")
    parser.add_argument("directory", help="The directory to search for .png files")
    args = parser.parse_args()

    directory = args.directory
    process_all_png_files(directory)
```

**Comment by michalpelka** [comment]
I have forced the main branch, removing the largest textures. We will re-write the main branch running compression and downsizing of all pngs.
