### ISSUE TITLE
Improve user experience with ros2_ws

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#203]
Use a single vsc import (change submodules to .repo file).
Use a single rosdep install all.

**Comment by jhanca-robotecai** [comment]
A single _bash_ script that pulls all submodules adequate to either `humble` or `iron` was added in #253. It also informs the user if failed or if ROS was not installed/sourced. I believe it solves this issue. Please reopen if needed.
