### ISSUE TITLE
Fix OTTO prefabs

### ISSUE THREAD

**Issue by pawelbudziszewski** [RobotecAI/ROSCon2023Demo#213]
In case of both OTTO prefabs:

1. LIDAR sensors are children of `base_link_visual`. Should be moved to `base_link`
![Screenshot from 2023-10-13 10-43-35](https://github.com/RobotecAI/ROSCon2023Demo/assets/31925544/a150c0d6-26a8-4bf3-a358-a9b870ea73b4)

2. Wheel meshes are inserted twice (in `base_link_visual` and in wheel visuals). This causes z-fighting
![Screenshot from 2023-10-13 10-43-04](https://github.com/RobotecAI/ROSCon2023Demo/assets/31925544/8b0dae8c-72e2-4362-851b-ffd95b9cc461)

**Comment by jhanca-robotecai** [comment]
There is one more problem with Otto 1500 model: it misses two Realsense cameras in the mesh. I believe @aniafafe was working on that, but I am not sure what is the status.
