### ISSUE TITLE
Check and clean submodules

### ISSUE THREAD

**Issue by jhanca-robotecai** [RobotecAI/ROSCon2023Demo#254]
Demo uses `git submodules` to pull `ros2_ws/src/moveit_task_constructor` and `ros2_ws/src/Universal_Robots_ROS2_Driver`.

The first one, however, does not exist. 
The second one, on the other hand, uses a fork instead of the official repository. 

Double-check what is wrong.

**Comment by jhanca-robotecai** [comment]
please note, that commit `698914b` exists on the source `ros2_ws/src/Universal_Robots_ROS2_Driver` repo, therefore fork might be not needed

**Comment by michalpelka** [comment]
I manually backported one of the fixes from the Iron branch to the Humble branch using forked Universal_Robots_ROS2_Driver. The backported fix was support for UR20. If these were done in the official repo, we can switch back to the official one.

**Comment by jhanca-robotecai** [comment]
> I manually backported one of the fixes from the Iron branch to the Humble branch using forked Universal_Robots_ROS2_Driver. The backported fix was support for UR20. If these were done in the official repo, we can switch back to the official one.

I see the change, but the `head` was never set to this commit:
![image](https://github.com/RobotecAI/ROSCon2023Demo/assets/134940295/321d0d04-1018-463d-9dbb-04bc8ba3867b)
