### ISSUE TITLE
Adjust vehicle to recent changes.

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/ROSCon2023Demo#283]
**Describe the issue**
I cannot run simulation with recent changes in o3de-extras development.

**Expected behavior**
Robots should move  navigate as in released version
**Actual behavior**
Otto 600 is missing its wheel controllers (that cause the robot to not move). After that, those robots work incorrently moving back and forth. Seems some bug in the odometry calculation that should be double-checked in o3de-extras.
**Steps to reproduce**
1. Try to compile against o3d-extras / o3de development.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branches**
I was testing PhysX 5 split PR.

**Desktop/Device (please complete the following information):**
 - OS [e.g. Windows 10 22H2, Ubuntu 22.04]
 - CPU [e.g. Intel I9-9900k, Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by jhanca-robotecai** [comment]
Is the issue solved by updates in https://github.com/RobotecAI/o3de-otto-robots-gem/pull/7 ?

**Comment by michalpelka** [comment]
It was solved by https://github.com/RobotecAI/o3de-otto-robots-gem/pull/7 .
