### ISSUE TITLE
Create ROS2 workspace

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/ROSCon2023Demo#3]
Please create a ROS2 workspace with the necessary packages for running the robot navigation motion/planning.

**Comment by arturkamieniecki** [comment]
Should the project be moved to a separate directory (like in https://github.com/o3de/ROSConDemo) to prevent the Asset Processor from compiling files such as images for readme, or files inside the ros2 workspace?

**Comment by arturkamieniecki** [comment]
Closed with #18.
