### ISSUE TITLE
Import many different robots 

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#42]
This will be used to test SDF / URDF import feature.

Not necessarily into the main scene at first, but into a separate level.

Compile the list of available / relevant URDFs first, around 10 robots.

**Comment by michalpelka** [comment]
Some of this work was done in https://github.com/RobotecAI/o3de-ros2-gem-testing/pull/9

**Comment by jhanca-robotecai** [comment]
This work was done in #176 and #227
