### ISSUE TITLE
Script behaviors which won't be controlled through ROS

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/ROSCon2023Demo#43]
- [x] Reasonable spawning of boxes on conveyor belts.
- [ ] Recovering from errors such as misaligned objects (design-first).
- [ ] Human Points of Interest based behavior and pathing.
- [x] Despawning of pallets with boxes when they reach a certain area (may be a box shape).

**Comment by adamdbrw** [comment]
Don't spawn boxes if there are X boxes already on the same conveyor belt.

**Comment by michalpelka** [comment]
Some portion of this work was done in #46
